"""add structured checkin fields

Revision ID: 8d85dbf4b632
Revises: e9439819b1a8
Create Date: 2026-03-09 16:31:45.848699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d85dbf4b632'
down_revision: Union[str, Sequence[str], None] = 'e9439819b1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('tasks_planned', sa.String(), nullable=True))
    op.add_column('checkins', sa.Column('next_week_plan', sa.String(), nullable=True))
    op.add_column('checkins', sa.Column('completion_status', sa.String(), nullable=True))
    op.add_column('checkins', sa.Column('contribution_type', sa.String(), nullable=True))
    op.add_column('checkins', sa.Column('confidence_level', sa.Integer(), nullable=True))
    op.add_column('checkins', sa.Column('blocked_by', sa.String(), nullable=True))
    op.add_column('checkins', sa.Column('needs_help', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'needs_help')
    op.drop_column('checkins', 'blocked_by')
    op.drop_column('checkins', 'confidence_level')
    op.drop_column('checkins', 'contribution_type')
    op.drop_column('checkins', 'completion_status')
    op.drop_column('checkins', 'next_week_plan')
    op.drop_column('checkins', 'tasks_planned')
    # ### end Alembic commands ###
