"""add teams table

Revision ID: e9439819b1a8
Revises: f7f2227a2df6
Create Date: 2026-03-07 23:02:22.074332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9439819b1a8'
down_revision: Union[str, Sequence[str], None] = 'f7f2227a2df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'match_run_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('teams_match_run_id_fkey'), 'teams', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('teams_match_run_id_fkey'), 'teams', 'matchruns', ['match_run_id'], ['id'])
    op.alter_column('teams', 'match_run_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
